//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://paqueteServicio/", ConfigurationName="ServiceReference1.ServicioWeb")]
    public interface ServicioWeb {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://paqueteServicio/)
        [System.ServiceModel.OperationContractAttribute(Action="http://paqueteServicio/ServicioWeb/SumaRequest", ReplyAction="http://paqueteServicio/ServicioWeb/SumaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Prueba.ServiceReference1.SumaResponse Suma(Prueba.ServiceReference1.SumaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://paqueteServicio/ServicioWeb/SumaRequest", ReplyAction="http://paqueteServicio/ServicioWeb/SumaResponse")]
        System.Threading.Tasks.Task<Prueba.ServiceReference1.SumaResponse> SumaAsync(Prueba.ServiceReference1.SumaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Suma", WrapperNamespace="http://paqueteServicio/", IsWrapped=true)]
    public partial class SumaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int numero1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int numero2;
        
        public SumaRequest() {
        }
        
        public SumaRequest(int numero1, int numero2) {
            this.numero1 = numero1;
            this.numero2 = numero2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumaResponse", WrapperNamespace="http://paqueteServicio/", IsWrapped=true)]
    public partial class SumaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public SumaResponse() {
        }
        
        public SumaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebChannel : Prueba.ServiceReference1.ServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebClient : System.ServiceModel.ClientBase<Prueba.ServiceReference1.ServicioWeb>, Prueba.ServiceReference1.ServicioWeb {
        
        public ServicioWebClient() {
        }
        
        public ServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prueba.ServiceReference1.SumaResponse Prueba.ServiceReference1.ServicioWeb.Suma(Prueba.ServiceReference1.SumaRequest request) {
            return base.Channel.Suma(request);
        }
        
        public int Suma(int numero1, int numero2) {
            Prueba.ServiceReference1.SumaRequest inValue = new Prueba.ServiceReference1.SumaRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            Prueba.ServiceReference1.SumaResponse retVal = ((Prueba.ServiceReference1.ServicioWeb)(this)).Suma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prueba.ServiceReference1.SumaResponse> Prueba.ServiceReference1.ServicioWeb.SumaAsync(Prueba.ServiceReference1.SumaRequest request) {
            return base.Channel.SumaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prueba.ServiceReference1.SumaResponse> SumaAsync(int numero1, int numero2) {
            Prueba.ServiceReference1.SumaRequest inValue = new Prueba.ServiceReference1.SumaRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            return ((Prueba.ServiceReference1.ServicioWeb)(this)).SumaAsync(inValue);
        }
    }
}
